### ISSUE TITLE
test_interruption_does_not_cleanup and test_functional_work_flow fails

### ISSUE THREAD

**Issue by mtelka** [pytest-dev/pytest-xprocess#113]
**Describe the bug**
When I run tests with Python 3.9.15 two tests fails.

**To Reproduce**
`tox-3.9 --current-env --no-provision --recreate -e py39`

**Expected behavior**
All tests pass

**Screenshots**
```
______________________ test_interruption_does_not_cleanup ______________________

testdir = <Testdir local('/tmp/pytest-of-marcel/pytest-33/test_interruption_does_not_cleanup0')>
tcp_port = 53786

    def test_interruption_does_not_cleanup(testdir, tcp_port):
        server_path = Path(__file__).parent.joinpath("server.py").absolute()
        testdir.makepyfile(
            """
            import sys
            import socket
            from xprocess import ProcessStarter
    
            def test_servers_start(request, xprocess):
                port = %r
                server_path = %r
    
                class Starter(ProcessStarter):
                    pattern = "started"
                    args = [sys.executable, server_path, port]
    
                xprocess.ensure("server_test_interrupt_no_terminate", Starter)
    
                raise KeyboardInterrupt
            """
            % (tcp_port, str(server_path))
        )
        result = testdir.runpytest_subprocess()
        result.stdout.fnmatch_lines("*KeyboardInterrupt*")
        result = testdir.runpytest("--xshow")
>       result.stdout.fnmatch_lines("*LIVE*")
E       Failed: remains unmatched: '*LIVE*'

$(BUILDPATH)/tests/test_interruption_clean_up.py:58: Failed
----------------------------- Captured stdout call -----------------------------
running: /usr/bin/python3.9 -mpytest --basetemp=/tmp/pytest-of-marcel/pytest-33/test_interruption_does_not_cleanup0/runpytest-0
     in: /tmp/pytest-of-marcel/pytest-33/test_interruption_does_not_cleanup0
__________________________ test_functional_work_flow ___________________________

testdir = <Testdir local('/tmp/pytest-of-marcel/pytest-33/test_functional_work_flow0')>
tcp_port = 42620

    def test_functional_work_flow(testdir, tcp_port):
        server_path = Path(__file__).parent.joinpath("server.py").absolute()
        testdir.makepyfile(
            """
            import sys
            import socket
            from xprocess import ProcessStarter
    
            def test_server(request, xprocess):
                port = %r
                data = "spam\\n"
                server_path = %r
    
                class Starter(ProcessStarter):
                    pattern = "started"
                    max_read_lines = 200
                    args = [sys.executable, server_path, port]
    
                # required so test won't hang on pytest_unconfigure
                xprocess.proc_wait_timeout = 1
    
                xprocess.ensure("server_workflow_test", Starter)
    
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
                    sock.connect(("localhost", port))
                    sock.sendall(bytes(data, "utf-8"))
                    received = str(sock.recv(1024), "utf-8")
                    assert received == data.upper()
        """
            % (tcp_port, str(server_path))
        )
        result = testdir.runpytest()
>       result.stdout.fnmatch_lines("*1 passed*")
E       Failed: remains unmatched: '*1 passed*'

$(BUILDPATH)/tests/test_functional_workflow.py:36: Failed
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/vendor-packages/_pytest/pytester.py", line 1170, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "/usr/lib/python3.9/vendor-packages/_pytest/pytester.py", line 1135, in inline_run
    ret = main([str(x) for x in args], plugins=plugins)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 148, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.9/vendor-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.9/vendor-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/lib/python3.9/vendor-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.9/vendor-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 1058, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 1346, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 1229, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3.9/vendor-packages/pluggy/_manager.py", line 288, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 489, in register
    ret: Optional[str] = super().register(plugin, name)
  File "/usr/lib/python3.9/vendor-packages/pluggy/_manager.py", line 103, in register
    hookimpl_opts = self.parse_hookimpl_opts(plugin, name)
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 460, in parse_hookimpl_opts
    return _get_legacy_hook_marks(
  File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 374, in _get_legacy_hook_marks
    warn_explicit_for(cast(FunctionType, method), message)
  File "/usr/lib/python3.9/vendor-packages/_pytest/warning_types.py", line 171, in warn_explicit_for
    raise type(w)(f"{w}\n at {filename}:{lineno}") from None
pytest.PytestDeprecationWarning: The hookimpl pytest_runtest_makereport uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(hookwrapper=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
$(INSTALLPATH)/usr/lib/python3.9/vendor-packages/xprocess/pytest_xprocess.py:48
```

**Environment (please complete the following information):**
 - OS: OpenIndiana
 - Python Version 3.9.15
 - pytest-xprocess version 0.20.0

**Additional context**
NA

**Comment by northernSage** [comment]
Thanks for taking the time to report the issue @mtelka

**Comment by mtelka** [comment]
I retested with 0.21.0 and both tests are still failing with basically the same error. :-(

**Comment by northernSage** [comment]
Then I'll ask you to please double check your environment and dependencies since both tests are passing just fine on py37, py38, py39 for all platforms in our CI with pytest==7.2.0.

https://github.com/pytest-dev/pytest-xprocess/actions/runs/3559144607
