### ISSUE TITLE
Spurious ResourceWarnings about unterminated processes

### ISSUE THREAD

**Issue by mal** [pytest-dev/pytest-xprocess#59]
**Description**
A `ResourceWarning` is triggered during tests using fixtures that start an xprocess. This seems like it might be a indication that Popen isn't being treated correctly and results in spurious user-facing errors when telling pytest to escalate warnings to errors.

**To Reproduce**

tests/conftest.py
```py
from pytest import fixture
from xprocess import ProcessStarter


@fixture # using (scope='session') results in similar behaviour but only for the first test to use the fixture
def example(xprocess):
    class Starter(ProcessStarter):
        pattern = "foo"
        args = ('sh', '-c', 'echo foo; sleep 10; echo bar')
    log = xprocess.ensure('example', Starter)
    yield
    xprocess.getinfo('example').terminate()
```

tests/pytest.ini
```ini
[pytest]
filterwarnings =
    error
```

tests/test_example.py
```py
def test_hello(example):
    pass

def test_world(example):
    pass
```

```
python3 -m pytest tests/test_example.py
```

**Expected behaviour**
No `ResourceWarning: subprocess X is still running` should occur until after the expected process termination has failed, at the end of the fixture's scope.

**Screenshots**
```
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function Popen.__del__ at 0x7f871d81d430>
E
E               Traceback (most recent call last):
E                 File "/usr/local/lib/python3.8/subprocess.py", line 942, in __del__
E                   _warn("subprocess %s is still running" % self.pid,
E               ResourceWarning: subprocess 376 is still running

/usr/local/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
```
```
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
E
E               Traceback (most recent call last):
E                 File "/usr/local/lib/python3.8/site-packages/xprocess.py", line 164, in ensure
E                   logfiles[name] = f
E               ResourceWarning: unclosed file <_io.TextIOWrapper name='/src/tests/.pytest_cache/d/.xprocess/example/xprocess.log' mode='r' encoding='UTF-8'>
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.8.6
 - pytest-xprocess: version 0.17.0

**Additional context**
```
platform linux -- Python 3.8.6, pytest-6.2.0, py-1.10.0, pluggy-0.13.1                                                                                                                                             
rootdir: /src/tests, configfile: pytest.ini                                                                                                                                                                        
plugins: xprocess-0.17.0
```

**Comment by northernSage** [comment]
Hey @mal, thanks for letting us know about this problem.

From [subprocess source code](https://github.com/python/cpython/blob/master/Lib/subprocess.py#L1063)
```python
# Not reading subprocess exit status creates a zombie process which
# is only destroyed at the parent python process exit
_warn("subprocess %s is still running" % self.pid,
    ResourceWarning, source=self)
```
The problemas was in the [XProcess.ensure](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L107) method where the created popen instance was not being correctly waited upon as instructed by suprocess. Simply calling [wait()](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait) on the process instance in `XProcess.__del__` method seems to have solved it.

I will release a fix for this soon. Once again, thanks for taking the time to open the issue 👍🏻
