### ISSUE TITLE
0.18.1: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest-xprocess#95]
**Describe the bug**
Looks like new pytest shows one unit failing.

**To Reproduce**
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

**Expected behavior**

**Screenshots**
Here is pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-xprocess-0.18.1-3.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-xprocess-0.18.1-3.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pytest-xprocess-0.18.1, configfile: tox.ini
plugins: xprocess-0.18.1
collected 45 items

tests/test_callback.py ......                                                                                                                                        [ 13%]
tests/test_functional_workflow.py .                                                                                                                                  [ 15%]
tests/test_interruption_clean_up.py F.                                                                                                                               [ 20%]
tests/test_process_initialization.py ...............                                                                                                                 [ 53%]
tests/test_process_termination.py ...............                                                                                                                    [ 86%]
tests/test_resource_cleanup.py ...                                                                                                                                   [ 93%]
tests/test_startup_timeout.py ...                                                                                                                                    [100%]

================================================================================= FAILURES =================================================================================
________________________________________________________________________ test_interruption_cleanup _________________________________________________________________________

cls = <class '_pytest.runner.CallInfo'>, func = <function call_runtest_hook.<locals>.<lambda> at 0x7f1b33a624c0>, when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        """Call func, wrapping the result in a CallInfo.

        :param func:
            The function to call. Called without arguments.
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

/usr/lib/python3.8/site-packages/_pytest/runner.py:338:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/site-packages/_pytest/runner.py:259: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
/usr/lib/python3.8/site-packages/pluggy/_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
/usr/lib/python3.8/site-packages/pluggy/_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:88: in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function Popen.__del__ at 0x7f1b34246f70>
E
E               Traceback (most recent call last):
E                 File "/usr/lib64/python3.8/subprocess.py", line 946, in __del__
E                   _warn("subprocess %s is still running" % self.pid,
E               ResourceWarning: subprocess 1673106 is still running

/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
--------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------
running: /usr/bin/python3 -mpytest --basetemp=/tmp/pytest-of-tkloczko/pytest-237/test_interruption_cleanup0/runpytest-0
     in: /tmp/pytest-of-tkloczko/pytest-237/test_interruption_cleanup0
============================= test session starts ==============================
platform linux -- Python 3.8.13, pytest-7.1.1, pluggy-1.0.0
rootdir: /tmp/pytest-of-tkloczko/pytest-237/test_interruption_cleanup0
plugins: xprocess-0.18.1
collected 1 item

test_interruption_cleanup.py

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/tmp/pytest-of-tkloczko/pytest-237/test_interruption_cleanup0/test_interruption_cleanup.py:16: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
============================ no tests ran in 0.42s =============================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
1673112 server_test_interrupt DEAD /tmp/pytest-of-tkloczko/pytest-237/test_interruption_cleanup0/.pytest_cache/d/.xprocess/server_test_interrupt/xprocess.log
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
========================================================================= short test summary info ==========================================================================
FAILED tests/test_interruption_clean_up.py::test_interruption_cleanup - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function Popen.__del__ at 0x7f1b3...
====================================================================== 1 failed, 44 passed in 40.34s =======================================================================
ocess_name>).terminate()'.
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-7f45f463-80bf-49d4-8af6-65ed5d4cc065
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-tkloczko/garbage-7f45f463-80bf-49d4-8af6-65ed5d4cc065'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-638dfb38-0e22-42fa-994b-6fa837a10eb9
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-tkloczko/garbage-638dfb38-0e22-42fa-994b-6fa837a10eb9'
  warnings.warn(
```
**Environment (please complete the following information):**
 - OS: Linux x86/64
 - Python Version: 3.8.13
 - pytest-xprocess version: 0.18.1

**Additional context**
List of modules installed in build env
```console

**Comment by kloczek** [comment]
Strange .. aftere add to --deselect failing unit another one popped up
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-xprocess-0.18.1-3.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-xprocess-0.18.1-3.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --deselect tests/test_interruption_clean_up.py::test_interruption_cleanup
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pytest-xprocess-0.18.1, configfile: tox.ini
plugins: xprocess-0.18.1
collected 45 items / 1 deselected / 44 selected

tests/test_callback.py ......                                                                                                                                        [ 13%]
tests/test_functional_workflow.py .                                                                                                                                  [ 15%]
tests/test_interruption_clean_up.py F                                                                                                                                [ 18%]
tests/test_process_initialization.py ...............                                                                                                                 [ 52%]
tests/test_process_termination.py ...............                                                                                                                    [ 86%]
tests/test_resource_cleanup.py ...                                                                                                                                   [ 93%]
tests/test_startup_timeout.py ...                                                                                                                                    [100%]

================================================================================= FAILURES =================================================================================
____________________________________________________________________ test_interruption_does_not_cleanup ____________________________________________________________________

cls = <class '_pytest.runner.CallInfo'>, func = <function call_runtest_hook.<locals>.<lambda> at 0x7f14d4a974c0>, when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        """Call func, wrapping the result in a CallInfo.

        :param func:
            The function to call. Called without arguments.
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

/usr/lib/python3.8/site-packages/_pytest/runner.py:338:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/site-packages/_pytest/runner.py:259: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
/usr/lib/python3.8/site-packages/pluggy/_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
/usr/lib/python3.8/site-packages/pluggy/_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:88: in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function Popen.__del__ at 0x7f14d527bf70>
E
E               Traceback (most recent call last):
E                 File "/usr/lib64/python3.8/subprocess.py", line 946, in __del__
E                   _warn("subprocess %s is still running" % self.pid,
E               ResourceWarning: subprocess 1679412 is still running

/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
--------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------
running: /usr/bin/python3 -mpytest --basetemp=/tmp/pytest-of-tkloczko/pytest-240/test_interruption_does_not_cleanup0/runpytest-0
     in: /tmp/pytest-of-tkloczko/pytest-240/test_interruption_does_not_cleanup0
============================= test session starts ==============================
platform linux -- Python 3.8.13, pytest-7.1.1, pluggy-1.0.0
rootdir: /tmp/pytest-of-tkloczko/pytest-240/test_interruption_does_not_cleanup0
plugins: xprocess-0.18.1
collected 1 item

test_interruption_does_not_cleanup.py

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/tmp/pytest-of-tkloczko/pytest-240/test_interruption_does_not_cleanup0/test_interruption_does_not_cleanup.py:15: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
============================ no tests ran in 0.40s =============================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
1679418 server_test_interrupt_no_terminate LIVE /tmp/pytest-of-tkloczko/pytest-240/test_interruption_does_not_cleanup0/.pytest_cache/d/.xprocess/server_test_interrupt_no_terminate/xprocess.log
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
1679418 server_test_interrupt_no_terminate TERMINATED
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
========================================================================= short test summary info ==========================================================================
FAILED tests/test_interruption_clean_up.py::test_interruption_does_not_cleanup - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <function Popen.__del__ a...
=============================================================== 1 failed, 43 passed, 1 deselected in 39.52s ================================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-f5ffadc9-8296-4f99-bc48-4ca776998fb7
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-tkloczko/garbage-f5ffadc9-8296-4f99-bc48-4ca776998fb7'
  warnings.warn(
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-tkloczko/garbage-472dc335-0a83-4732-ad1b-f87eaff7562f
<class 'OSError'>: [Errno 39] Directory not empty: '/tmp/pytest-of-tkloczko/garbage-472dc335-0a83-4732-ad1b-f87eaff7562f'
  warnings.warn(
```
I think that some units may have some dependencies.
Using `pytest-randomly` may expose all those issues.
If that would be the issue https://github.com/mrbean-bremen/pytest-find-dependencies/ could be used.

**Comment by kloczek** [comment]
BTW .. looks like version in documentation is always one version behind 😋 
https://github.com/pytest-dev/pytest-xprocess/blob/6ecca0c229ad7100d6167c518ce40f1aaa126492/docs/source/conf.py#L21

**Comment by kloczek** [comment]
> BTW .. looks like version in documentation is always one version behind 😋

Any comment about taht small issue? 😃

**Comment by dvzrv** [comment]
This is still an issue with 0.23.0
